export const provincesWithCitiesAndAddressesMock = [
  { name: 'Buenos Aires' },
  { name: 'Córdoba' },
  { name: 'Santa Fe' },
  { name: 'Mendoza' },
  { name: 'Tucumán' },
  { name: 'Salta' },
  { name: 'Entre Ríos' },
  { name: 'Chaco' },
  { name: 'Corrientes' },
  { name: 'Misiones' },
  { name: 'San Juan' },
  { name: 'San Luis' },
  { name: 'Jujuy' },
  { name: 'Neuquén' },
  { name: 'Río Negro' },
  { name: 'La Pampa' },
  { name: 'Chubut' },
  { name: 'Formosa' },
  { name: 'Catamarca' },
  { name: 'La Rioja' },
  { name: 'Santa Cruz' },
  { name: 'Tierra del Fuego' },
];
