import { ApiProperty } from '@nestjs/swagger';
import { IsString, IsUrl, IsUUID } from 'class-validator';

export class CreatePaymentPreferenceResponseDto {
  @ApiProperty({
    description: 'The unique identifier of the order for which the payment was created.',
    example: 'a1b2c3d4-e5f6-7890-1234-567890abcdef',
  })
  @IsUUID()
  orderId: string;

  @ApiProperty({
    description: 'The unique identifier of the payment preference generated by the provider (e.g., Mercado Pago).',
    example: '123456789-abcdef12-3456-7890-abcd-ef1234567890',
  })
  @IsString()
  preferenceId: string;

  @ApiProperty({
    description: 'The URL to which the user should be redirected to complete the payment.',
    example: 'https://www.mercadopago.com.ar/checkout/v1/redirect?pref_id=...',
  })
  @IsUrl()
  paymentLink: string;

  constructor(partial: Partial<CreatePaymentPreferenceResponseDto>) {
    Object.assign(this, partial);
  }
}