name: ci-cd-staging

on:
  push:
    branches: staging


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:   
      -  
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build and push docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/ecommerce-platform:latest
          build-args:  |
            NODE_ENV=${{ github.ref_name == 'main' && 'production' || 'development' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      ##Deploy to render

     ## me: Deploy to render
     ##es: johnbeynon/render-deploy-action@v0.0.8
    ##  with:
    ##    service-id: ${{secrets.RENDER_SERVICE_ID}}
    ##    api-key: ${{secrets.RENDER_API_KEY}}
    ##    wait-for-success: true